version: '1.0'
profile:
  name: qodana.starter
include:
  - name: RegExpSimplifiable
exclude:
  - name: All
    paths:
      - node_modules
      - qodana_results
      - qodana_final_report
  - name: HardcodedPasswords
    paths:
      - package.json
